# Generated by Django 3.2 on 2022-04-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blosh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comments',
        ),
    ]
