# Generated by Django 3.2 on 2022-04-20 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blosh', '0002_remove_blog_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='blog_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
