# Generated by Django 3.2 on 2022-04-20 23:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blosh', '0005_alter_blog_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comments',
        ),
        migrations.AddField(
            model_name='blog',
            name='user_comments',
            field=models.ManyToManyField(blank=True, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
