# Generated by Django 3.2 on 2022-04-20 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blosh', '0006_auto_20220420_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user_comments',
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blosh.blog'),
        ),
    ]
